/** The sample pack's customer and instalment references (see presentationSamples in lib/presenter-brief.ts). */
export const PRESENTATION_CUSTOMER = 'PRES-C001';
export const PRESENTATION_INSTALMENT = 'PRES-D001';

/** Presenter guidance describes existing workflows; it is never operational evidence. */
export const presentationSteps = [
  { title: 'Start with the work', time: '45 sec', href: '/overview', action: 'Open overview', value: 'Know what needs attention before the day begins.', show: 'Name the selected sample lender. Point out outstanding obligations, matches to review and open exceptions.', say: 'Valo Pay brings payment evidence and the work around it into one place for a lender’s Operations and Finance teams.', fallback: 'Use the figures currently on screen. These are synthetic records, not customer traction or measured savings.' },
  { title: 'Bring in payment evidence', time: '60 sec', href: '/imports', action: 'Open import batches', value: 'Check records before they affect the books.', show: 'Open the prepared payment batch. Show the naira amount and row checks before committing it once.', say: 'A file is checked and saved with its source. An error can be corrected before the batch is committed.', fallback: 'If the file was already committed, show its saved result and provenance. Do not change source identities just to import it again.' },
  // The sample payment names its instalment and equals it, so rule R1 matches it automatically and with certainty: it is never
  // in Matches to review. Its match and explanation are in the sample customer's history, which the guide opens once imported.
  { title: 'Explain the match', time: '90 sec', href: `/customers?q=${PRESENTATION_CUSTOMER}`, customer: PRESENTATION_CUSTOMER, action: 'Open the sample customer', value: 'Connect a receipt to the obligation it covers.', show: `After committing the payment file, run reconciliation on the Reconciliation page if your role permits it. Then open the sample customer ${PRESENTATION_CUSTOMER} and its history. The payment names instalment ${PRESENTATION_INSTALMENT} and the amounts are equal, so rule R1 matched them automatically and with certainty. The history shows the match with its rule and explanation. It never appears in Matches to review, which holds only matches Finance must confirm.`, say: 'When a payment names the instalment it pays and the amounts agree, the match is made automatically and recorded with its reason. A less certain match waits for Finance to confirm it instead of being accepted silently.', fallback: `If the customer is not found, the sample files have not been imported for this lender: import them first. If the payment is still unallocated, reconciliation has not run since the import; run it. To show a match that waits for Finance, open Matches to review in Reconciliation and say it is a seeded payment, not the sample one. If access is refused, explain the role requirement; do not change permissions for the presentation.` },
  { title: 'Give an exception an owner', time: '60 sec', href: '/exceptions', action: 'Open exceptions', value: 'Turn an unresolved item into accountable work.', show: 'Choose a separate open sample exception. Show the customer, owner and deadline, then open its case history.', say: 'When something needs investigation, the next person can see the context, the next action and the handover history.', fallback: 'If no exceptions are open, show a resolved case. Recording a resolution does not execute a payment or establish missing evidence.' },
  { title: 'Review the day’s close', time: '60 sec', href: '/reports#daily-closes', action: 'Open daily closes', value: 'Separate a recorded close from an independently reviewed close.', show: 'Open a rehearsed daily close and its source coverage. Use Close review to show what Finance accepted or returned.', say: 'A close freezes the evidence available at that time. Missing sources remain visible, and review is a separate decision.', fallback: 'A missing source or pending review is a useful control to explain. Never describe it as complete. A second demo role alone does not satisfy independent approval.' },
  { title: 'Leave with the evidence', time: '45 sec', href: '/exports', action: 'Open saved exports', value: 'Make the work inspectable after the meeting.', show: 'Open a prepared export for this lender. Show its saved status and download the ready file. Use a customer timeline if you want to start a new dispute pack.', say: 'Evidence can be retrieved after the session. Its saved status shows whether generation finished or needs recovery.', fallback: 'If an export is still running, show its actual status and use the previously downloaded sample file. Do not describe a queued file as ready.' },
] as const;

export const presentationChecks = [
  { id: 'build', label: 'I opened the intended build and checked the pages I will show.' },
  { id: 'lender', label: 'I chose one sample lender and checked my actual permissions.' },
  { id: 'records', label: 'I rehearsed the import, match and case I will use.' },
  { id: 'close', label: 'I checked the close’s actual source coverage and review status.' },
  { id: 'backup', label: 'I downloaded a sample export and prepared a backup recording or screenshots.' },
  { id: 'claims', label: 'I will identify sample figures and explain the outstanding live dependencies.' },
] as const;
