# Generated by Django 5.2.17 on 2026-10-03 20:56

import core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('external_id', models.CharField(max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Meridian Finance', max_length=120)),
                ('retry_preset', models.CharField(default='Standard', max_length=12)),
                ('receipts', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=60)),
                ('product', models.CharField(default='Personal finance', max_length=80)),
                ('status', models.CharField(default='Open', max_length=20)),
                ('on_hold', models.BooleanField(default=False)),
                ('hold_reason', models.TextField(blank=True)),
                ('consent_status', models.CharField(default='Not requested', max_length=20)),
                ('consent_max', models.BigIntegerField(default=0)),
                ('consent_expiry', models.DateField(null=True)),
                ('consent_token', models.CharField(default=core.models.token, max_length=80, unique=True)),
                ('consent_requested_at', models.DateTimeField(null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='core.customer')),
                ('held_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.member')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organisation')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organisation'),
        ),
        migrations.CreateModel(
            name='Instalment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('amount', models.BigIntegerField()),
                ('paid', models.BigIntegerField(default=0)),
                ('state', models.CharField(default='Upcoming', max_length=25)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instalments', to='core.loan')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organisation')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organisation'),
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=120)),
                ('detail', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('previous_hash', models.CharField(blank=True, max_length=64)),
                ('digest', models.CharField(max_length=64)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organisation')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=80, unique=True)),
                ('amount', models.BigIntegerField()),
                ('status', models.CharField(default='Confirmed', max_length=25)),
                ('source', models.CharField(default='Direct debit', max_length=30)),
                ('paid_at', models.DateTimeField()),
                ('sample', models.BooleanField(default=True)),
                ('instalment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.instalment')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organisation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=80, unique=True)),
                ('amount', models.BigIntegerField()),
                ('status', models.CharField(default='Awaiting approval', max_length=30)),
                ('expires_at', models.DateTimeField()),
                ('token', models.CharField(default=core.models.token, max_length=80, unique=True)),
                ('instalment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.instalment')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=50)),
                ('amount', models.BigIntegerField(default=0)),
                ('status', models.CharField(default='Open', max_length=20)),
                ('deadline', models.DateTimeField()),
                ('evidence', models.TextField()),
                ('note', models.TextField(blank=True)),
                ('outcome', models.CharField(blank=True, max_length=50)),
                ('instalment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.instalment')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organisation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_reviews', to='core.member')),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_reviews', to='core.member')),
                ('resolved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_reviews', to='core.member')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('reason', models.TextField()),
                ('status', models.CharField(default='Requested', max_length=20)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organisation')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.payment')),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.review')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.UniqueConstraint(fields=('organisation', 'reference'), name='vp_loan_id'),
        ),
        migrations.AddConstraint(
            model_name='instalment',
            constraint=models.UniqueConstraint(fields=('loan', 'sequence'), name='vp_schedule_sequence'),
        ),
        migrations.AddConstraint(
            model_name='instalment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0), ('paid__gte', 0), ('paid__lte', models.F('amount'))), name='vp_valid_money'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('organisation', 'external_id'), name='vp_customer_id'),
        ),
        migrations.AddConstraint(
            model_name='paymentrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['Awaiting approval', 'Awaiting confirmation', 'Unknown'])), fields=('instalment',), name='vp_one_active_request'),
        ),
    ]
