# Generated by Django 5.2.17 on 2026-10-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_importpreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='actor_user_id',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='after_state',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='audit',
            name='before_state',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='audit',
            name='customer_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='audit',
            name='entity_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='audit',
            name='entity_type',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='audit',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='schema_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
