# Generated by Django 5.2.17 on 2026-10-04 07:11

import django.utils.timezone
from django.db import migrations, models


def mark_existing_demo(apps, schema_editor):
    # Until now the demo seeder was the only way to create an organisation, so every existing one is a demo workspace.
    apps.get_model("core", "Organisation").objects.update(demo=True)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="demo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organisation",
            name="last_seen_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RunPython(mark_existing_demo, migrations.RunPython.noop),
    ]
