# Generated by Django 5.2.17 on 2026-10-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_accessrate_accesstoken_staffmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='action',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='target',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
