# Generated by Django 5.2.17 on 2026-10-03 22:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_member_user_member_vp_real_actor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportPreview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_digest', models.CharField(max_length=64)),
                ('content_digest', models.CharField(max_length=64)),
                ('row_count', models.PositiveIntegerField()),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organisation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
