import { useState } from "react";
import type { SourceManifestInput } from "@workspace/valopay-schema";
import { usePilotMutation } from "@/lib/pilot";
import { useUnsavedChanges } from "@/lib/unsaved-changes";
import { PilotPanel, RecoveryNotice, pilotField } from "@/components/pilot-ui";
import { Button } from "@/components/ui/button";
import { formatKobo } from "@/lib/formatters";
import { Link } from "wouter";
import { nairaToKobo, koboToNaira } from "@/lib/money-input";

const kinds = { customers:"Customers", mandates:"Mandates", "due-items":"Instalments", attempts:"Collection attempts", observations:"Payment evidence" };
export function SourceCompletenessPanel({ completeness, frozen = false }: { completeness: any; frozen?: boolean }) {
  return <PilotPanel title="Business-date source completeness">
    <p className="text-sm">{completeness.businessDate} · WAT · {completeness.completeFiles} of {completeness.expectedFiles} expected files complete</p>
    <p className="text-sm text-muted-foreground">A file counts only when its declared business date, source ID, committed row count and original amount total agree. Upload time does not identify the day it covers.</p>
    {frozen && <p className="text-sm text-muted-foreground">This is the source evidence recorded with this close. Financial totals reflect the close run, not a backdated financial period. Later source changes require a new close.</p>}
    {completeness.status === "complete" ? <p className="rounded-lg bg-success/10 p-3 text-sm">Every declared file is committed and its source totals agree.</p> : <div className="space-y-2">{completeness.issues.map((issue:any) => <div key={issue.id} className="rounded-lg border border-warning-border bg-warning/10 p-3 text-sm"><p className="font-medium">{issue.label}</p><p className="mt-1 text-muted-foreground">{issue.detail}</p></div>)}</div>}
    {!!completeness.files.length && <div className="grid gap-3 lg:grid-cols-2">{completeness.files.map((file:any) => <article key={file.id} className="rounded-lg border p-3 text-sm"><p className="font-medium">{file.sourceBatchId} · {file.status === "complete" ? "Complete" : "Incomplete"}</p><p className="text-muted-foreground">{file.source} · {kinds[file.kind as keyof typeof kinds]}</p><p className="mt-2">Declared: {file.expectedRows} rows · {formatKobo(file.expectedAmountKobo)}</p><p>Received: {file.receivedRows ?? "—"} rows · {file.receivedAmountKobo == null ? "—" : formatKobo(file.receivedAmountKobo)}</p><Link href={file.batchId ? `/imports?batch=${encodeURIComponent(file.batchId)}` : `/imports?businessDate=${completeness.businessDate}&expectation=${file.id}`} className="mt-2 inline-flex min-h-10 items-center text-primary underline">{file.batchId ? "Inspect source batch" : "Import expected file"}</Link></article>)}</div>}
    {completeness.manifest && <details className="rounded-lg border p-3 text-sm"><summary className="cursor-pointer min-h-8 font-medium">Declaration evidence · revision {completeness.manifest.data.revision}</summary><p className="whitespace-pre-wrap">{completeness.manifest.data.reason}</p><p className="mt-2 break-words text-muted-foreground">Evidence: {completeness.manifest.data.evidence}</p><p className="mt-2 text-muted-foreground">Declared by {completeness.manifest.data.declaredBy}. Earlier revisions remain in the audit record.</p></details>}
    <Link href={frozen ? `/sources?businessDate=${completeness.businessDate}` : "/close-review"} className="inline-flex min-h-10 items-center text-sm text-primary underline">{frozen ? "Open current source declarations for this date" : "Review the close and any source exceptions"}</Link>
  </PilotPanel>;
}
export function SourceManifestEditor({ completeness }: { completeness: any }) {
  type FileDraft = SourceManifestInput["files"][number] & { amountNaira:string };
  const previous = completeness.manifest, [files,setFiles] = useState<FileDraft[]>(() => (previous?.data.files || []).map(({source,sourceBatchId,kind,expectedRows,expectedAmountKobo}:any)=>({source,sourceBatchId,kind,expectedRows,expectedAmountKobo,amountNaira:koboToNaira(expectedAmountKobo)}))), [excluded,setExcluded] = useState(Boolean(previous?.data.noFilesExpected)), [reason,setReason] = useState(""), [evidence,setEvidence] = useState(""), [dirty,setDirty] = useState(false), [amountErrors,setAmountErrors]=useState<Record<number,string>>({});
  const mutation = usePilotMutation(()=>setDirty(false)), busy=mutation.isPending||mutation.hasUnconfirmedOutcome;
  useUnsavedChanges(dirty);
  const change = (index:number, patch:Partial<FileDraft>) => {setFiles(value=>value.map((file,i)=>i===index?{...file,...patch}:file));setAmountErrors(value=>{const next={...value};delete next[index];return next;});setDirty(true);};
  return <PilotPanel title={previous ? "Revise the expected source files" : "Declare the expected source files"}><p className="text-sm text-muted-foreground">Declare the complete file set and control totals from the source owner for {completeness.businessDate}. A revision preserves the previous declaration and requires a new close. If no files are expected, Finance must explicitly accept that exclusion.</p>
    <form className="space-y-4" onSubmit={event=>{event.preventDefault();const errors:Record<number,string>={},declaredFiles=excluded?[]:files.map(({amountNaira,...file},index)=>{try{return {...file,expectedAmountKobo:file.kind==='customers'?0:nairaToKobo(amountNaira)};}catch(error){errors[index]=(error as Error).message;return file;}});setAmountErrors(errors);if(Object.keys(errors).length)return;mutation.mutate({path:"/sources/manifests",data:{businessDate:completeness.businessDate,files:declaredFiles,noFilesExpected:excluded,reason,evidence,previousManifestId:previous?.id,expectedUpdatedAt:previous?.updatedAt,syntheticOnly:true}});}}>
      <fieldset disabled={busy} className="space-y-4"><label className="flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" checked={excluded} onChange={event=>{setExcluded(event.target.checked);setDirty(true);}}/>No source files are expected for this business date</label>
      {!excluded && <div className="space-y-3">{files.map((file,index)=><fieldset key={index} className="rounded-lg border p-4"><legend className="px-1 text-sm font-medium">Expected file {index+1}</legend><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
        <label className="text-sm">Expected file source {index+1}<input className={pilotField} required maxLength={100} value={file.source} onChange={e=>change(index,{source:e.target.value})}/></label>
        <label className="text-sm">Expected source batch ID {index+1}<input className={pilotField} required maxLength={120} value={file.sourceBatchId} onChange={e=>change(index,{sourceBatchId:e.target.value})}/></label>
        <label className="text-sm">Expected record type {index+1}<select className={pilotField} value={file.kind} onChange={e=>change(index,{kind:e.target.value as any,...(e.target.value==='customers'?{expectedAmountKobo:0,amountNaira:'0.00'}:{})})}>{Object.entries(kinds).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
        <label className="text-sm">Declared row count {index+1}<input className={pilotField} type="number" required min={0} max={500} step={1} value={file.expectedRows} onChange={e=>change(index,{expectedRows:Number(e.target.value)})}/></label>
        <div><label className="text-sm" htmlFor={`source-file-amount-${index}`}>Declared total (₦) {index+1}</label><input id={`source-file-amount-${index}`} className={pilotField} inputMode="decimal" required disabled={file.kind==='customers'} value={file.amountNaira} aria-invalid={!!amountErrors[index]} aria-describedby={amountErrors[index]?`source-file-amount-error-${index}`:undefined} onChange={e=>change(index,{amountNaira:e.target.value})} onBlur={()=>{try{nairaToKobo(file.amountNaira);}catch(error){setAmountErrors(value=>({...value,[index]:(error as Error).message}));}}}/>{amountErrors[index]&&<p id={`source-file-amount-error-${index}`} role="alert" className="mt-1 text-sm text-destructive">{amountErrors[index]}</p>}</div>
        <Button type="button" variant="outline" className="self-end" onClick={()=>{setFiles(value=>value.filter((_,i)=>i!==index));setAmountErrors({});setDirty(true);}}>Remove expected file {index+1}</Button></div></fieldset>)}<Button type="button" variant="outline" disabled={files.length>=100} onClick={()=>{setFiles(value=>[...value,{source:"",sourceBatchId:"",kind:"customers",expectedRows:0,expectedAmountKobo:0,amountNaira:'0.00'}]);setDirty(true);}}>Add expected file</Button></div>}
      <label className="block text-sm">Declaration reason<textarea required minLength={10} maxLength={3000} className={pilotField} value={reason} onChange={e=>{setReason(e.target.value);setDirty(true);}} placeholder="What confirms this is the complete expected file set, or why are no files expected?"/></label>
      <label className="block text-sm">Supporting source evidence<input required minLength={5} maxLength={1000} className={pilotField} value={evidence} onChange={e=>{setEvidence(e.target.value);setDirty(true);}} placeholder="Source control report, agreed delivery list or recorded confirmation reference"/></label>
      <Button type="submit" busy={mutation.isPending} disabled={!excluded&&!files.length}>Save source declaration</Button></fieldset><RecoveryNotice mutation={mutation}/>
    </form>
  </PilotPanel>;
}
