import { useState } from 'react';
import { Link } from 'wouter';
import { ArrowRight, Check, Download, FileText, Play, Presentation } from 'lucide-react';
import { useWorkspace } from '@/lib/workspace-context';
import { usePresentation, usePresentationHref } from '@/components/presentation-guide';
import { presentationChecks, presentationSteps, presentationSamples, presenterBrief, downloadPresentationFile } from '@/lib/presentation';
import { Button } from '@/components/ui/button';

export default function PresentationPage() {
  const { state, save } = usePresentation();
  const { workspace, merchantId } = useWorkspace();
  const [date] = useState(() => new Date(Date.now() + 3_600_000).toISOString().slice(0, 10));
  const [notice, setNotice] = useState('');
  const lender = workspace?.merchants.find(m => m.id === merchantId);
  const hrefFor = usePresentationHref(true);
  function download(filename: string, content: string, csv = false) {
    try { downloadPresentationFile(filename, content, csv); setNotice(`Download requested: ${filename}. Check your browser’s downloads.`); }
    catch { setNotice('The download could not start. Try again or use the guidance on this page.'); }
  }
  return <div className="space-y-8 pb-8">
    <section className="relative overflow-hidden rounded-2xl border bg-card p-6 sm:p-8">
      <div className="mb-5 inline-flex items-center gap-2 rounded-full border bg-background px-3 py-1.5 text-xs font-medium"><Presentation className="h-4 w-4 text-primary" aria-hidden="true" />Investor demonstration · About 6 minutes</div>
      <div className="grid gap-7 lg:grid-cols-[1.5fr_1fr]">
        <div><h1 className="max-w-xl text-3xl font-semibold tracking-tight sm:text-4xl">Show how a lender gets from records to a reviewed close.</h1><p className="mt-4 max-w-xl text-sm leading-6 text-muted-foreground">One lender’s working day: check the evidence, explain the match, assign the exception and leave a clear record.</p>
          <div className="mt-6 flex flex-wrap gap-3"><Button disabled={!merchantId || workspace?.environment !== 'sandbox'} onClick={() => save({ ...state, active: true, step: 0 })}><Play className="mr-2 h-4 w-4" aria-hidden="true" />Start presentation guide</Button><Button variant="outline" onClick={() => download('valo-pay-presenter-brief.md', presenterBrief(date))}><Download className="mr-2 h-4 w-4" aria-hidden="true" />Download presenter brief</Button></div>
          <p className="mt-3 text-xs leading-5 text-muted-foreground">Starting the guide only opens navigation and talking points. Actions on the workflow pages use the normal checks and permissions.</p>
        </div>
        <aside className="rounded-xl border bg-secondary/25 p-5"><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Your rehearsal workspace</p><p className="mt-3 text-xl font-semibold">{lender?.name || 'Choose a sample lender'}</p><p className="mt-2 text-sm">{workspace?.accessMode === 'staff' ? 'Staff role' : 'Demo role'}: {workspace?.role || 'Not available'}</p><p className="mt-4 border-t pt-4 text-sm leading-6 text-muted-foreground">Synthetic data. No money moves. Figures on screen illustrate the workflow; they are not traction, recovery uplift or live payment results.</p><Link href="/pilot" className="mt-3 inline-flex min-h-10 items-center gap-2 text-sm font-medium text-primary underline underline-offset-4">Open pilot setup<ArrowRight className="h-4 w-4" aria-hidden="true" /></Link></aside>
      </div>
    </section>

    <section aria-labelledby="demo-story"><div className="mb-4 flex flex-wrap items-end justify-between gap-2"><div><p className="text-xs font-semibold uppercase tracking-wider text-primary">The product story</p><h2 id="demo-story" className="mt-2 text-2xl font-semibold tracking-tight">Six moments that explain the value</h2></div><p className="text-sm text-muted-foreground">Open a workflow when you are ready.</p></div>
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{presentationSteps.map((step, index) => <article key={step.href} className="flex flex-col rounded-xl border bg-card p-5"><div className="flex items-center justify-between"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-primary/10 text-sm font-semibold text-primary">0{index + 1}</span><span className="text-xs text-muted-foreground">{step.time}</span></div><h3 className="mt-4 font-semibold">{step.title}</h3><p className="mt-2 flex-1 text-sm leading-6 text-muted-foreground">{step.value}</p><Link href={hrefFor(step)} className="mt-4 inline-flex min-h-10 items-center gap-2 text-sm font-medium text-primary underline underline-offset-4" onClick={() => save({ ...state, step: index })}>{step.action}<ArrowRight className="h-4 w-4" aria-hidden="true" /></Link></article>)}</div>
    </section>

    <div className="grid items-start gap-6 lg:grid-cols-2">
      <section aria-labelledby="demo-checks" className="rounded-xl border bg-card p-5 sm:p-6"><h2 id="demo-checks" className="text-lg font-semibold">Before you share your screen</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Your own checks for this session and lender. These do not verify service health, complete operational tasks or approve a pilot.</p><p aria-live="polite" className="mt-3 text-sm font-medium">{state.checked.length} of {presentationChecks.length} preparation checks marked</p><div className="mt-3 divide-y">{presentationChecks.map(check => <label key={check.id} className="flex cursor-pointer items-start gap-3 py-3 text-sm leading-6"><input type="checkbox" className="mt-1 h-4 w-4 shrink-0 accent-primary" checked={state.checked.includes(check.id)} onChange={e => save({ ...state, checked: e.target.checked ? [...state.checked, check.id] : state.checked.filter(id => id !== check.id) })} /><span>{check.label}</span></label>)}</div><Button size="sm" variant="ghost" onClick={() => save({ ...state, checked: [] })}>Clear preparation checks</Button><p className="mt-1 text-xs text-muted-foreground">This clears only the checkboxes. Saved platform records remain in place.</p></section>
      <section aria-labelledby="demo-pack" className="rounded-xl border bg-card p-5 sm:p-6"><h2 id="demo-pack" className="text-lg font-semibold">A repeatable sample import</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Prepare the customer and instalment before the meeting. Show the payment file during the demo. Each amount is <strong className="text-foreground">₦18,000.50</strong>; the pack’s business date is {date} (WAT).</p><ol className="mt-4 space-y-3">{presentationSamples(date).map((sample, index) => <li key={sample.filename} className="flex flex-wrap items-center justify-between gap-2 rounded-lg border p-3"><span className="flex items-center gap-2 text-sm"><FileText className="h-4 w-4 text-muted-foreground" aria-hidden="true" />{index + 1}. {sample.kind}</span><Button size="sm" variant="outline" onClick={() => download(sample.filename, sample.csv, true)} aria-label={`Download ${sample.kind.toLowerCase()} CSV`}><Download className="mr-2 h-4 w-4" aria-hidden="true" />CSV</Button></li>)}</ol><details className="mt-4 text-sm"><summary className="min-h-10 cursor-pointer py-2 font-medium">Import instructions and repeat rehearsals</summary><p className="mt-2 leading-6">In Import batches, choose each matching record type and Naira. Use source name “Presentation sample”, source row column “source_row_id” and a different file reference for each CSV. Set business date {date}. Save and check, inspect the preview, then commit once. Reconcile the payment separately.</p><p className="mt-3 leading-6 text-muted-foreground">Repeated files keep their source identities and may be reported as duplicates. For a fresh run, use a separate anonymous browser session or a new empty synthetic lender. An empty lender has no sample exceptions until you prepare them. Keep existing workspaces intact.</p></details></section>
    </div>

    <section aria-labelledby="demo-boundaries" className="rounded-xl border bg-card p-5 sm:p-6"><h2 id="demo-boundaries" className="text-lg font-semibold">Keep the claims as clear as the product</h2><div className="mt-4 grid gap-6 md:grid-cols-3"><div><h3 className="flex items-center gap-2 text-sm font-semibold"><Check className="h-4 w-4 text-primary" aria-hidden="true" />Demonstrate in the sandbox</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Saved imports, matching explanations, assigned cases, close evidence and retrievable exports. Show the actual status of each record.</p></div><div><h3 className="text-sm font-semibold">Explain what still needs verification</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">External Paystack connectivity, staff identity and MFA, managed keys, restricted database access, recovery and live acceptance on the intended host.</p></div><div><h3 className="text-sm font-semibold">Bring separate commercial evidence</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Customer conversations, signed agreements and measured pilot outcomes, where available. Sample totals and completed preparation checks do not establish these.</p></div></div></section>
    <p role="status" className="text-sm text-muted-foreground">{notice}</p>
  </div>;
}
